# Generated by Django 2.2.5 on 2019-09-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_casino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='image',
            field=models.ImageField(blank=True, upload_to='casino_logos/', verbose_name='Logo'),
        ),
    ]
