# Generated by Django 2.2.5 on 2019-10-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190914_2309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Casino',
        ),
    ]
