# Generated by Django 2.2.5 on 2019-10-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Casino title')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('casino_country', models.CharField(blank=True, max_length=100, verbose_name='Country of casino')),
                ('banned_countries', models.TextField(blank=True, verbose_name='Banned countries by casino')),
                ('ca_license', models.CharField(blank=True, default='', max_length=100, verbose_name='License')),
                ('crypto', models.BooleanField(default=False, verbose_name='Cryptocasino')),
                ('scam', models.BooleanField(default=False, verbose_name='Scam')),
                ('script', models.BooleanField(default=False, verbose_name='Script')),
                ('link', models.URLField(blank=True, max_length=300, verbose_name="Casino's Link")),
                ('dol', models.DateField(verbose_name='Date of launching')),
                ('image', models.ImageField(blank=True, upload_to='casino_logos/', verbose_name='Logo')),
                ('rate_soft', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Software rate')),
                ('rate_design', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Design rate')),
                ('rate_safe', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Safe rate')),
                ('rate_faith', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Faith rate')),
                ('rate', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Main rate')),
                ('short_desc', models.TextField(blank=True, max_length=1024, verbose_name='Short description')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('pros_c', models.TextField(blank=True, verbose_name='Pros')),
                ('cons_c', models.TextField(blank=True, verbose_name='Cons')),
                ('jackpot', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Jackpot value')),
                ('limit_in', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Input limit')),
                ('limit_out', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Output limit')),
                ('docs', models.BooleanField(default=True, verbose_name='Documents for withdrawal')),
                ('day_witdrawals', models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Withdrawal count per day')),
                ('week_witdrawals', models.PositiveSmallIntegerField(blank=True, default=7, verbose_name='Withdrawal count per week')),
                ('accepted_payments', models.TextField(blank=True, verbose_name='Payment processing')),
            ],
            options={
                'ordering': ['rate'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Payment method name')),
                ('image', models.ImageField(upload_to='payment_logos/', verbose_name='Payment method image(PNG)')),
                ('is_crypto', models.BooleanField(default=False, verbose_name='Is it cryptocurrency??')),
                ('casino', models.ManyToManyField(to='casinos.Casino')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_word_desc', models.CharField(default='Нет бонусов', max_length=300, verbose_name='About the bonus in 2 words')),
                ('bonus_digit', models.PositiveSmallIntegerField(verbose_name='Bonus amount')),
                ('bonus_desc', models.TextField(blank=True, verbose_name='Bonus description')),
                ('dep_bool', models.BooleanField(default=True)),
                ('dep', models.PositiveSmallIntegerField()),
                ('casino', models.ManyToManyField(to='casinos.Casino')),
            ],
        ),
    ]
