# Generated by Django 2.2.5 on 2019-10-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='accepted_payments',
        ),
        migrations.AlterField(
            model_name='payment',
            name='image',
            field=models.ImageField(blank=True, upload_to='payment_logos/', verbose_name='Payment method image(PNG)'),
        ),
    ]
