# Generated by Django 2.2.5 on 2019-10-05 09:33

import casinos.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0002_auto_20191004_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='casino',
            name='day_witdrawals',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='limit_in',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='limit_out',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='week_witdrawals',
        ),
        migrations.AddField(
            model_name='casino',
            name='cashback',
            field=models.BooleanField(default=False, verbose_name='Does it have cashback?'),
        ),
        migrations.AddField(
            model_name='casino',
            name='max_output',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Max Output'),
        ),
        migrations.AddField(
            model_name='casino',
            name='min_in',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Min limit/deposit'),
        ),
        migrations.AddField(
            model_name='casino',
            name='min_output',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Min Output'),
        ),
        migrations.AddField(
            model_name='casino',
            name='russian_support',
            field=models.BooleanField(default=False, verbose_name='Russian support?'),
        ),
        migrations.AddField(
            model_name='casino',
            name='support',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024, verbose_name='Support grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casino',
            name='witdrawal',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Witdrawal frequency(d,w)'),
        ),
        migrations.AddField(
            model_name='casino',
            name='with_docs_bool',
            field=models.BooleanField(default=True, verbose_name='Casino wants docs to withdrawal?'),
        ),
        migrations.AddField(
            model_name='casino',
            name='with_easy',
            field=models.CharField(default='Средняя', max_length=50, verbose_name='How easy to withdrawal(Easy, Meidum, Hard, Extrahard)'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='dol',
            field=models.PositiveIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(1984), casinos.models.max_value_current_year], verbose_name='Date of launching'),
        ),
    ]
