# Generated by Django 2.2.5 on 2019-10-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0004_auto_20191005_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='jackpot',
            field=models.CharField(blank=True, max_length=20, verbose_name='Jackpot value'),
        ),
    ]
