# Generated by Django 2.2.5 on 2019-10-10 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0005_auto_20191005_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casino',
            old_name='russian_support',
            new_name='rus_support',
        ),
        migrations.RenameField(
            model_name='casino',
            old_name='support',
            new_name='support_desc',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='casino_country',
        ),
        migrations.AddField(
            model_name='casino',
            name='support_grade',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Customer support grade'),
        ),
        migrations.AddField(
            model_name='license',
            name='casino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casinos.Casino'),
        ),
        migrations.AddField(
            model_name='license',
            name='description',
            field=models.TextField(blank=True, verbose_name="License's description"),
        ),
        migrations.AddField(
            model_name='license',
            name='name',
            field=models.CharField(default='Отсутствует', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='license',
            name='validation_link',
            field=models.URLField(blank=True, max_length=300, verbose_name='Validation Link'),
        ),
        migrations.AddField(
            model_name='software',
            name='casino',
            field=models.ManyToManyField(blank=True, to='casinos.Casino'),
        ),
        migrations.AddField(
            model_name='software',
            name='description',
            field=models.TextField(blank=True, max_length=1024, verbose_name="Game's description"),
        ),
        migrations.AddField(
            model_name='software',
            name='icon',
            field=models.ImageField(blank=True, upload_to='software_icons/'),
        ),
        migrations.AddField(
            model_name='software',
            name='name',
            field=models.CharField(default='Отсутствует', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Отсутствует', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=1024, verbose_name="Game's description")),
                ('icon', models.ImageField(blank=True, upload_to='software_icons/')),
                ('casino', models.ManyToManyField(blank=True, to='casinos.Casino')),
            ],
        ),
    ]
