# Generated by Django 2.2.5 on 2019-10-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0007_auto_20191014_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casino',
            old_name='witdrawal',
            new_name='with_freq',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='docs',
        ),
        migrations.AlterField(
            model_name='casino',
            name='banned_countries',
            field=models.TextField(blank=True, verbose_name='Banned players from ...'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='cashback',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cashback'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='crypto',
            field=models.BooleanField(default=False, verbose_name='Cryptocasino?'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='jackpot',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Jackpot value'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='link',
            field=models.URLField(blank=True, max_length=300, verbose_name='Casino Link'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='scam',
            field=models.BooleanField(default=False, verbose_name='Scam?'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='script',
            field=models.BooleanField(default=False, verbose_name='Script?'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='with_easy',
            field=models.CharField(max_length=50, verbose_name='How easy to withdrawal(Легко, Средне, Сложно, Суперсложно)'),
        ),
    ]
