# Generated by Django 2.2.5 on 2019-10-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0008_auto_20191014_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='image_hg',
            field=models.PositiveSmallIntegerField(blank=True, default=100, null=True, verbose_name='Image height(in pixels)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='image_wd',
            field=models.PositiveSmallIntegerField(blank=True, default=100, null=True, verbose_name='Image width(in pixels)'),
        ),
    ]
