# Generated by Django 2.2.5 on 2019-10-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0009_auto_20191016_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['-bonus_digit']},
        ),
        migrations.AddField(
            model_name='casino',
            name='ca_license_bool',
            field=models.BooleanField(default=False, max_length=100, verbose_name='License Y/N'),
        ),
        migrations.AddField(
            model_name='casino',
            name='cashback_bool',
            field=models.BooleanField(default=False, verbose_name='Cashback Y/N'),
        ),
        migrations.AddField(
            model_name='casino',
            name='jackpot_value',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Jackpot value in digits($)'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='bonus_digit',
            field=models.PositiveSmallIntegerField(verbose_name='Bonus value'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='ca_license',
            field=models.CharField(blank=True, default='Нет', max_length=100, null=True, verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='cashback',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cashback value'),
        ),
    ]
