# Generated by Django 2.2.5 on 2019-10-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0010_auto_20191022_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='jackpot_bool',
            field=models.BooleanField(default=False, verbose_name='Jackpot Y/N'),
        ),
    ]
