# Generated by Django 3.0.4 on 2020-08-13 01:26

import casinos.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0011_casino_jackpot_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='dol',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1984), casinos.models.max_value_current_year], verbose_name='Date of launching'),
        ),
        migrations.DeleteModel(
            name='License',
        ),
    ]
