# Generated by Django 3.1 on 2020-08-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0012_auto_20200813_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCasino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
