# Generated by Django 3.1 on 2020-08-25 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0013_topcasino'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casino',
            options={'ordering': ['-rate']},
        ),
        migrations.AlterModelOptions(
            name='topcasino',
            options={'ordering': ['sponsored', 'casino']},
        ),
        migrations.AddField(
            model_name='topcasino',
            name='casino',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='casinos.casino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topcasino',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='casino',
            name='banned_countries',
            field=models.TextField(blank=True, verbose_name='Banned players from'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='ca_license_bool',
            field=models.BooleanField(default=False, max_length=100, verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='casino_logos/'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='link',
            field=models.URLField(blank=True, max_length=300, verbose_name='Affiliate link'),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pole', models.CharField(choices=[('NEUTRAL', 'NEUTRAL'), ('PROS', 'PROS'), ('CONS', 'CONS')], default='NEUTRAL', max_length=20)),
                ('casino', models.ManyToManyField(related_name='features', to='casinos.Casino')),
            ],
        ),
    ]
