# Generated by Django 3.1 on 2020-08-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0017_auto_20200828_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casino',
            options={},
        ),
        migrations.RemoveField(
            model_name='casino',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='rate_design',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='rate_faith',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='rate_safe',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='rate_soft',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='image_hg',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='image_wd',
        ),
        migrations.AlterField(
            model_name='bonus',
            name='bonus_desc',
            field=models.TextField(blank=True, verbose_name='Bonus Description'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='two_word_desc',
            field=models.CharField(default='No bonuses', max_length=300),
        ),
        migrations.AlterField(
            model_name='casino',
            name='image',
            field=models.ImageField(upload_to='casino_logos/'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='with_easy',
            field=models.CharField(max_length=50, verbose_name='How easy to withdrawal?'),
        ),
        migrations.AlterField(
            model_name='game',
            name='casino',
            field=models.ManyToManyField(blank=True, null=True, to='casinos.Casino'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='software_icons/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='casino',
            field=models.ManyToManyField(blank=True, null=True, to='casinos.Casino'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_logos/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_crypto',
            field=models.BooleanField(default=False, verbose_name='Is it crypto ?'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='casino',
            field=models.ManyToManyField(blank=True, null=True, to='casinos.Casino'),
        ),
        migrations.AlterField(
            model_name='software',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='software_icons/'),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
