# Generated by Django 3.0.4 on 2020-08-13 01:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20200813_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentrate',
            name='author',
        ),
        migrations.AddField(
            model_name='commentrate',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='commentrate',
            name='comment',
        ),
        migrations.AddField(
            model_name='commentrate',
            name='comment',
            field=models.ManyToManyField(to='blog.Comment'),
        ),
    ]
