# Generated by Django 3.0.4 on 2020-08-13 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20200813_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentrate',
            name='author',
        ),
        migrations.AddField(
            model_name='commentrate',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='commentrate',
            name='comment',
        ),
        migrations.AddField(
            model_name='commentrate',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
        ),
    ]
