# Generated by Django 3.0.4 on 2020-08-13 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200813_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrate',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='blog.Comment'),
        ),
    ]
