# Generated by Django 3.1 on 2020-08-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200821_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentrate',
            name='author',
        ),
        migrations.RemoveField(
            model_name='commentrate',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentRate',
        ),
    ]
