# Generated by Django 3.1 on 2020-08-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200821_1922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_on',
            new_name='updated',
        ),
    ]
