# Generated by Django 3.1 on 2020-08-24 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
